server:
  port: 8081
  servlet:
    session:
      timeout: 15m
      cookie:
        http-only: true
        secure: true
#日志等级
logging:
  level:
    com:
      example:
        demo:
          mapper: debug

spring:
  security:
    loginType: JSON

  session:
    timeout: 15m

  servlet:
    session:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mygratuation?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root

mybatis:
  type-aliases-package: com.xiaochao.pojo
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: xiaochao
  expiration: 3600000
  header: JWTHeaderName